# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Test

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - run: |
            npm install
            NODE_ENV=production SENDGRID_API_KEY=off ELEPHANT_URL=${{ secrets.ELEPHANT_URL_TEST}} PORT=3000 npm start & sleep 10
    - run: | 
        mkdir -p testResults
        node_modules/.bin/newman run test/COVID19_the_game_villain.postman_collection.json --env-var url=http://0.0.0.0:3000 -r cli,htmlextra --reporter-htmlextra-export testResults/htmlreport.html  
    
    # Upload the contents of Test Results directory to workspace
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: testResults

    # Run Java restAssure test
    - name: Run Java restAssure test
      uses: actions/setup-java@v1
      with:
        java-version: '20'
    - run: | 
        cd restassured-project
        mvn clean test